name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Use 'temurin' instead of 'adoptopenjdk'

      - name: Build with Maven
        working-directory: ./ci-cd-demo
        run: mvn clean install

      - name: Run tests
        run: mvn test
